# Generated by Django 5.1.3 on 2024-11-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employersignup',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
