# Generated by Django 5.1.3 on 2024-11-18 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_employersignup_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employersignup',
            name='address',
        ),
    ]
